/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author FG
 */
public class FrmAbout extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    private Connection conn;

    public FrmAbout(Connection conn) {
        this.conn = conn;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AMA | v.1");
        setMinimumSize(new java.awt.Dimension(1070, 800));
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/AMA - About Us.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 320, 410, 90);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/AMA - 3 Admin.gif"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 410, 450, 150);

        jLabel1.setFont(new java.awt.Font("Orator Std", 0, 15)); // NOI18N
        jLabel1.setText("C O D I N G ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 560, 110, 30);

        jLabel7.setFont(new java.awt.Font("Orator Std", 0, 15)); // NOI18N
        jLabel7.setText("C O D I N G ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 560, 130, 30);

        jLabel8.setFont(new java.awt.Font("Orator Std", 0, 14)); // NOI18N
        jLabel8.setText("D E S I G N E R");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, 560, 130, 30);

        jLabel5.setFont(new java.awt.Font("Orator Std", 0, 15)); // NOI18N
        jLabel5.setText("JEFFREY.A");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 590, 100, 20);

        jLabel6.setFont(new java.awt.Font("Orator Std", 0, 15)); // NOI18N
        jLabel6.setText("FENDY.G");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(350, 590, 80, 20);

        jLabel9.setFont(new java.awt.Font("Orator Std", 0, 15)); // NOI18N
        jLabel9.setText("HENRY.T");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 590, 80, 20);

        jLabel11.setFont(new java.awt.Font("Orator Std", 0, 24)); // NOI18N
        jLabel11.setText(" be part of the solution\"");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 680, 370, 40);

        jLabel12.setFont(new java.awt.Font("Orator Std", 0, 24)); // NOI18N
        jLabel12.setText("\"whatever the problem");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 630, 310, 40);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/tumblr_nkqtlyLSDt1u68awfo1_400.gif"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(420, 550, 340, 210);

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/back-icon-2.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        getContentPane().add(lblBack);
        lblBack.setBounds(10, 30, 130, 100);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Address.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(-10, 320, 1080, 10);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/ezgif.com-resize (1).gif"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 1060, 320);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/background.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1070, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        this.setVisible(false);
        FrmMain fm = new FrmMain();
        fm.setVisible(true);
        fm.txtID.requestFocusInWindow();
    }//GEN-LAST:event_lblBackMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBack;
    // End of variables declaration//GEN-END:variables
}
