/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import util.*;
import main.*;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author FG
 */
public class FrmRegistration extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    private Connection conn;

    public FrmRegistration(Connection conn) {
        this.conn = conn;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpGender = new javax.swing.ButtonGroup();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPass2 = new javax.swing.JPasswordField();
        rdoFemale = new javax.swing.JRadioButton();
        rdoMale = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtUID = new javax.swing.JTextField();
        dtcDOB = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        txtPOB = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPass1 = new javax.swing.JPasswordField();
        chkCertify = new javax.swing.JCheckBox();
        btnRegister1 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AMA | v.1");
        setMinimumSize(new java.awt.Dimension(1070, 800));
        getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Re-enter password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 550, 140, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Gender");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 430, 80, 30);

        txtPass2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPass2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPass2);
        txtPass2.setBounds(160, 550, 300, 30);

        rdoFemale.setBackground(new java.awt.Color(255, 255, 255));
        btnGrpGender.add(rdoFemale);
        rdoFemale.setText("Female");
        getContentPane().add(rdoFemale);
        rdoFemale.setBounds(260, 430, 90, 25);

        rdoMale.setBackground(new java.awt.Color(255, 255, 255));
        btnGrpGender.add(rdoMale);
        rdoMale.setText("Male");
        getContentPane().add(rdoMale);
        rdoMale.setBounds(160, 430, 60, 25);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Name");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 340, 60, 30);

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(160, 340, 250, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Username");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 390, 110, 30);

        txtUID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtUID);
        txtUID.setBounds(160, 390, 250, 30);
        getContentPane().add(dtcDOB);
        dtcDOB.setBounds(260, 470, 200, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Place/Date of birth");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 470, 140, 30);

        txtPOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPOBActionPerformed(evt);
            }
        });
        getContentPane().add(txtPOB);
        txtPOB.setBounds(160, 470, 90, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Password");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 510, 80, 30);

        txtPass1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPass1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPass1);
        txtPass1.setBounds(160, 510, 300, 30);

        chkCertify.setBackground(new java.awt.Color(255, 255, 255));
        chkCertify.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        chkCertify.setText("I agree to the terms of service");
        chkCertify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCertifyActionPerformed(evt);
            }
        });
        getContentPane().add(chkCertify);
        chkCertify.setBounds(160, 590, 223, 25);

        btnRegister1.setBackground(new java.awt.Color(255, 255, 255));
        btnRegister1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRegister1.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/AMA - CREATE ACCOUNT.png"))); // NOI18N
        btnRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegister1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister1);
        btnRegister1.setBounds(160, 620, 220, 70);

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/Back.jpg"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(750, 630, 200, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/AMA - WELCOME.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 230, 420, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/background.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, -240, 1350, 1150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtUIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUIDActionPerformed

    private void txtPOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPOBActionPerformed

    private void txtPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPass2ActionPerformed

    }//GEN-LAST:event_txtPass2ActionPerformed

    private void txtPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPass1ActionPerformed

    private void chkCertifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCertifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCertifyActionPerformed

    private void btnRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegister1ActionPerformed
        String date = ((JTextField) dtcDOB.getDateEditor().getUiComponent()).getText();

        if (!chkCertify.isSelected()) {
            Sutil.msg(this, "Please agree to our terms in order to continue.");
        } else {
            if ((!txtName.getText().trim().isEmpty()) && (!txtPOB.getText().trim().isEmpty()) && (!txtPass1.getText().trim().isEmpty()) && (!txtPass2.getText().trim().isEmpty()) && (!txtPOB.getText().trim().isEmpty()) && (rdoMale.isSelected() || rdoFemale.isSelected()) &&!date.isEmpty()) {
              if (!txtPass1.getText().trim().toString().equals(txtPass2.getText().trim().toString())) {
              Sutil.msg(this, "Password do not match");
              }else{
                  try {
                      executeRegister();
                      this.setVisible(false);
                      FrmMain main= new FrmMain();
                      main.setVisible(true);
                  } catch (SQLException ex) {
                      Logger.getLogger(FrmRegistration.class.getName()).log(Level.SEVERE, null, ex);
                  }
              }
                
        }else{
                Sutil.msg(this, "Some field is still empty.");
            }
        }
    }//GEN-LAST:event_btnRegister1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        FrmMain main = new FrmMain();
        main.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.ButtonGroup btnGrpGender;
    private javax.swing.JButton btnRegister1;
    private javax.swing.JCheckBox chkCertify;
    private com.toedter.calendar.JDateChooser dtcDOB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rdoFemale;
    private javax.swing.JRadioButton rdoMale;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPOB;
    private javax.swing.JPasswordField txtPass1;
    private javax.swing.JPasswordField txtPass2;
    private javax.swing.JTextField txtUID;
    // End of variables declaration//GEN-END:variables

    private void executeActivate() {

    }

    private void executeRegister() throws SQLException {
        String insertSql = "INSERT INTO akuntansi.member "
                + "(nama,uid,gender,pob,dob,password)"
                + "VALUES (?,?,?,?,?,?);";
        PreparedStatement pstatement = conn.prepareStatement(insertSql);
        pstatement.setString(1, txtName.getText().trim());
        pstatement.setString(2, txtUID.getText().trim().toLowerCase());
        if (rdoMale.isSelected()) {
            pstatement.setString(3, "Male");
        } else if (rdoFemale.isSelected()) {
            pstatement.setString(3, "Female");
        }

        pstatement.setString(4, txtPOB.getText().trim());
        pstatement.setObject(5, dtcDOB.getDate());
        pstatement.setString(6, txtPass2.getText().trim());
        pstatement.executeUpdate();
        pstatement.close();
        Sutil.msg(this, "You have been registered. Now please login again.");
    }
}
